/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.yunpos.putianapp;

public final class R {
    public static final class anim {
        public static final int activity_close_enter=0x7f040000;
        public static final int activity_close_exit=0x7f040001;
        public static final int activity_open_enter=0x7f040002;
        public static final int activity_open_exit=0x7f040003;
        public static final int alpha=0x7f040004;
        public static final int alpha_in=0x7f040005;
        public static final int cycle_7=0x7f040006;
        public static final int decelerate_quint=0x7f040007;
        public static final int pophidden_anim=0x7f040008;
        public static final int popshow_anim=0x7f040009;
        public static final int shake_x=0x7f04000a;
    }
    public static final class attr {
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int behindOffset=0x7f010003;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int behindScrollScale=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int behindWidth=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fadeDegree=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fadeEnabled=0x7f01000a;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>left</code></td><td>0</td><td></td></tr>
<tr><td><code>right</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int mode=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int selectorDrawable=0x7f01000d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int selectorEnabled=0x7f01000c;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int shadowDrawable=0x7f010008;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int shadowWidth=0x7f010009;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int touchModeAbove=0x7f010006;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int touchModeBehind=0x7f010007;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int viewAbove=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int viewBehind=0x7f010002;
    }
    public static final class color {
        public static final int app_background=0x7f060000;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f070000;
        public static final int activity_vertical_margin=0x7f070001;
        public static final int bottom_tab_font_size=0x7f070006;
        public static final int bottom_tab_padding_drawable=0x7f070004;
        public static final int bottom_tab_padding_up=0x7f070005;
        public static final int shadow_width=0x7f070002;
        public static final int slidingmenu_offset=0x7f070003;
    }
    public static final class drawable {
        public static final int home_btn_bg=0x7f020000;
        public static final int home_btn_bg_s=0x7f020001;
        public static final int ic_launcher=0x7f020002;
        public static final int icon_tabitem_home_normal=0x7f020003;
        public static final int menu_bg=0x7f020004;
        public static final int menu_bg_hover=0x7f020005;
        public static final int shadow=0x7f020006;
        public static final int shadowright=0x7f020007;
        public static final int transparent=0x7f020008;
    }
    public static final class id {
        public static final int action_settings=0x7f05000f;
        public static final int btn_group=0x7f050006;
        public static final int content_frame=0x7f05000b;
        public static final int content_view=0x7f050005;
        public static final int frag_contact=0x7f05000a;
        public static final int frag_dail=0x7f050007;
        public static final int frag_records=0x7f050008;
        public static final int frag_text=0x7f050009;
        public static final int fullscreen=0x7f050003;
        public static final int left=0x7f050000;
        public static final int margin=0x7f050002;
        public static final int menu_frame=0x7f05000c;
        public static final int right=0x7f050001;
        public static final int selected_view=0x7f050004;
        public static final int slidingmenumain=0x7f05000e;
        public static final int textView1=0x7f05000d;
    }
    public static final class integer {
        public static final int activity_anim_duration=0x7f080000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int center_fragment=0x7f030001;
        public static final int content_frame=0x7f030002;
        public static final int discount_fragment=0x7f030003;
        public static final int discovery_fragment=0x7f030004;
        public static final int menu_frame=0x7f030005;
        public static final int realize_putian_fragment=0x7f030006;
        public static final int right_fragment=0x7f030007;
        public static final int shopping_fragment=0x7f030008;
        public static final int slidingmenumain=0x7f030009;
    }
    public static final class menu {
        public static final int main=0x7f0b0000;
    }
    public static final class string {
        public static final int action_settings=0x7f090001;
        public static final int app_name=0x7f090000;
        public static final int hello_world=0x7f090002;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f0a0000;
        /**  Application theme. 
         */
        public static final int AppTheme=0x7f0a0001;
        public static final int main_tab_bottom=0x7f0a0002;
    }
    public static final class styleable {
        /** Attributes that can be used with a SlidingMenu.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #SlidingMenu_behindOffset com.yunpos.putianapp:behindOffset}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_behindScrollScale com.yunpos.putianapp:behindScrollScale}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_behindWidth com.yunpos.putianapp:behindWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_fadeDegree com.yunpos.putianapp:fadeDegree}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_fadeEnabled com.yunpos.putianapp:fadeEnabled}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_mode com.yunpos.putianapp:mode}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_selectorDrawable com.yunpos.putianapp:selectorDrawable}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_selectorEnabled com.yunpos.putianapp:selectorEnabled}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_shadowDrawable com.yunpos.putianapp:shadowDrawable}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_shadowWidth com.yunpos.putianapp:shadowWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_touchModeAbove com.yunpos.putianapp:touchModeAbove}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_touchModeBehind com.yunpos.putianapp:touchModeBehind}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_viewAbove com.yunpos.putianapp:viewAbove}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_viewBehind com.yunpos.putianapp:viewBehind}</code></td><td></td></tr>
           </table>
           @see #SlidingMenu_behindOffset
           @see #SlidingMenu_behindScrollScale
           @see #SlidingMenu_behindWidth
           @see #SlidingMenu_fadeDegree
           @see #SlidingMenu_fadeEnabled
           @see #SlidingMenu_mode
           @see #SlidingMenu_selectorDrawable
           @see #SlidingMenu_selectorEnabled
           @see #SlidingMenu_shadowDrawable
           @see #SlidingMenu_shadowWidth
           @see #SlidingMenu_touchModeAbove
           @see #SlidingMenu_touchModeBehind
           @see #SlidingMenu_viewAbove
           @see #SlidingMenu_viewBehind
         */
        public static final int[] SlidingMenu = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b,
            0x7f01000c, 0x7f01000d
        };
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#behindOffset}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.yunpos.putianapp:behindOffset
        */
        public static final int SlidingMenu_behindOffset = 3;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#behindScrollScale}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.yunpos.putianapp:behindScrollScale
        */
        public static final int SlidingMenu_behindScrollScale = 5;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#behindWidth}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.yunpos.putianapp:behindWidth
        */
        public static final int SlidingMenu_behindWidth = 4;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#fadeDegree}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.yunpos.putianapp:fadeDegree
        */
        public static final int SlidingMenu_fadeDegree = 11;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#fadeEnabled}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.yunpos.putianapp:fadeEnabled
        */
        public static final int SlidingMenu_fadeEnabled = 10;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#mode}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>left</code></td><td>0</td><td></td></tr>
<tr><td><code>right</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.yunpos.putianapp:mode
        */
        public static final int SlidingMenu_mode = 0;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#selectorDrawable}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.yunpos.putianapp:selectorDrawable
        */
        public static final int SlidingMenu_selectorDrawable = 13;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#selectorEnabled}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.yunpos.putianapp:selectorEnabled
        */
        public static final int SlidingMenu_selectorEnabled = 12;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#shadowDrawable}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.yunpos.putianapp:shadowDrawable
        */
        public static final int SlidingMenu_shadowDrawable = 8;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#shadowWidth}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.yunpos.putianapp:shadowWidth
        */
        public static final int SlidingMenu_shadowWidth = 9;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#touchModeAbove}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.yunpos.putianapp:touchModeAbove
        */
        public static final int SlidingMenu_touchModeAbove = 6;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#touchModeBehind}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.yunpos.putianapp:touchModeBehind
        */
        public static final int SlidingMenu_touchModeBehind = 7;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#viewAbove}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.yunpos.putianapp:viewAbove
        */
        public static final int SlidingMenu_viewAbove = 1;
        /**
          <p>This symbol is the offset where the {@link com.yunpos.putianapp.R.attr#viewBehind}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.yunpos.putianapp:viewBehind
        */
        public static final int SlidingMenu_viewBehind = 2;
    };
}
